In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age','Outcome']
df = pd.read_csv(url, names=columns)
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [13]:
from sklearn.model_selection import train_test_split
X=df.drop('Outcome',axis=1)
y=df['Outcome']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train = X_train.copy()
X_test = X_test.copy()

This dataset is in need of some preprocessing.
Values that are 0 in columns other than Pregnancies and Outcome are actually NaN

In [14]:
nancols = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']
X_train[nancols] = X_train[nancols].replace(0,np.nan)
X_train.head()
X_test[nancols] = X_test[nancols].replace(0,np.nan)
X_test.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
668,6.0,98.0,58.0,33.0,190.0,34.0,0.430,43.0
324,2.0,112.0,75.0,32.0,125.0,35.7,0.148,21.0
624,2.0,108.0,64.0,29.0,125.0,30.8,0.158,21.0
690,8.0,107.0,80.0,29.0,125.0,24.6,0.856,34.0
473,7.0,136.0,90.0,29.0,125.0,29.9,0.210,50.0

In [20]:
#time to impute the NaNs with the median
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="median")
X_train_imp = imputer.fit_transform(X_train)
X_test_imp = imputer.transform(X_test)

In [41]:
#scaling values
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_std_lr = pd.DataFrame(scaler.fit_transform(X_train_imp), columns=X_train.columns, index=X_train.index)
X_test_std_lr = pd.DataFrame(scaler.transform(X_test_imp), columns=X_test.columns, index=X_test.index)
X_train_std_knn = X_train_std_lr.copy()
X_test_std_knn = X_test_std_lr.copy()
X_train_std.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
60,-0.526397,-1.256881,-0.018995,0.034298,-0.175620,-0.007450,-0.490735,-1.035940
618,1.588046,-0.326051,0.808174,-0.560583,-0.175620,-0.599092,2.415030,1.487101
346,-0.828460,0.571536,-2.169636,-1.155463,-0.652193,-0.526941,0.549161,-0.948939
294,-1.130523,1.302903,-1.838768,0.034298,-0.175620,-1.508200,-0.639291,2.792122
231,0.681856,0.405316,0.642740,0.986106,2.604392,1.998360,-0.686829,1.139095

MODEL 1: LOGISTIC REGRESSION FROM SCRATCH

In [42]:
class LogisticRegression:
  def __init__(self, lr=0.01, iterations=5000, threshold=0.5):
    self.lr = lr
    self.iterations = iterations
    self.threshold = threshold

  @staticmethod
  def sigmoid(z):
    z = np.clip(z,-500,500)
    return (1.0/(1.0 + np.exp(-z)))

  def fit(self, X, y):
    self.w = np.zeros(X.shape[1])
    self.b=0
    for i in range(self.iterations):
      z = X@self.w + self.b
      p = self.sigmoid(z)
      error = p - y
      grad_w = (X.T@error)/X.shape[0]
      grad_b = error.mean()
      self.w = self.w - self.lr*grad_w
      self.b = self.b - self.lr*grad_b
      cost_function = -np.mean(y*np.log(p) + (1-y)*np.log(1-p))
      if(i%10==0):
        print(f"Iteration {i} : Cost Function : {cost_function}")
    return self
  def predict(self,X):
    return (self.sigmoid(X@self.w  +self.b) >= self.threshold).astype(int)

In [43]:
y_pred = LogisticRegression(0.05,10000).fit(X_train_std,y_train).predict(X_test_std)

Iteration 0 : Cost Function : 0.6931471805599453
Iteration 10 : Cost Function : 0.6299138159637914
Iteration 20 : Cost Function : 0.5898629266053922
Iteration 30 : Cost Function : 0.5631104035359222
Iteration 40 : Cost Function : 0.5442968089317138
Iteration 50 : Cost Function : 0.5304735772487611
Iteration 60 : Cost Function : 0.5199472710687983
Iteration 70 : Cost Function : 0.5116969414206818
Iteration 80 : Cost Function : 0.5050779601763292
Iteration 90 : Cost Function : 0.4996660223766785
Iteration 100 : Cost Function : 0.49517142495949884
Iteration 110 : Cost Function : 0.49138994185213253
Iteration 120 : Cost Function : 0.4881735439026292
Iteration 130 : Cost Function : 0.485412308917103
Iteration 140 : Cost Function : 0.4830228754131396
Iteration 150 : Cost Function : 0.4809408529413774
Iteration 160 : Cost Function : 0.47911569878495763
Iteration 170 : Cost Function : 0.47750717550190014
Iteration 180 : Cost Function : 0.47608284780399285
Iteration 190 : Cost Function : 0.4748162788166108
Iteration 200 : Cost Function : 0.47368570707005314
Iteration 210 : Cost Function : 0.47267306042188134
Iteration 220 : Cost Function : 0.47176321036830465
Iteration 230 : Cost Function : 0.47094340068452395
Iteration 240 : Cost Function : 0.47020280438854617
Iteration 250 : Cost Function : 0.46953217646319506
Iteration 260 : Cost Function : 0.4689235789348227
Iteration 270 : Cost Function : 0.46837016125643066
Iteration 280 : Cost Function : 0.46786598340845403
Iteration 290 : Cost Function : 0.46740587231540454
Iteration 300 : Cost Function : 0.46698530447797704
Iteration 310 : Cost Function : 0.46660030940351943
Iteration 320 : Cost Function : 0.46624738966298074
Iteration 330 : Cost Function : 0.465923454333344
Iteration 340 : Cost Function : 0.4656257632873219
Iteration 350 : Cost Function : 0.4653518803275044
Iteration 360 : Cost Function : 0.46509963357353823
Iteration 370 : Cost Function : 0.46486708182952696
Iteration 380 : Cost Function : 0.4646524859074152
Iteration 390 : Cost Function : 0.4644542840774133
Iteration 400 : Cost Function : 0.4642710709709331
Iteration 410 : Cost Function : 0.46410157938434454
Iteration 420 : Cost Function : 0.4639446645301442
Iteration 430 : Cost Function : 0.46379929036118567
Iteration 440 : Cost Function : 0.4636645176575338
Iteration 450 : Cost Function : 0.4635394936174354
Iteration 460 : Cost Function : 0.4634234427362709
Iteration 470 : Cost Function : 0.4633156587920959
Iteration 480 : Cost Function : 0.4632154977849684
Iteration 490 : Cost Function : 0.46312237170089265
Iteration 500 : Cost Function : 0.46303574299081046
Iteration 510 : Cost Function : 0.4629551196713984
Iteration 520 : Cost Function : 0.4628800509680621
Iteration 530 : Cost Function : 0.46281012343196365
Iteration 540 : Cost Function : 0.4627449574725305
Iteration 550 : Cost Function : 0.46268420425502194
Iteration 560 : Cost Function : 0.4626275429195952
Iteration 570 : Cost Function : 0.46257467808415487
Iteration 580 : Cost Function : 0.46252533759823555
Iteration 590 : Cost Function : 0.4624792705194141
Iteration 600 : Cost Function : 0.4624362452873787
Iteration 610 : Cost Function : 0.46239604807390566
Iteration 620 : Cost Function : 0.46235848128967644
Iteration 630 : Cost Function : 0.46232336223118864
Iteration 640 : Cost Function : 0.46229052185301445
Iteration 650 : Cost Function : 0.4622598036524043
Iteration 660 : Cost Function : 0.4622310626547373
Iteration 670 : Cost Function : 0.46220416448964113
Iteration 680 : Cost Function : 0.46217898454874823
Iteration 690 : Cost Function : 0.46215540721706205
Iteration 700 : Cost Function : 0.4621333251707876
Iteration 710 : Cost Function : 0.46211263873525094
Iteration 720 : Cost Function : 0.4620932552972155
Iteration 730 : Cost Function : 0.46207508876650205
Iteration 740 : Cost Function : 0.4620580590823476
Iteration 750 : Cost Function : 0.4620420917604089
Iteration 760 : Cost Function : 0.4620271174767298
Iteration 770 : Cost Function : 0.46201307168536215
Iteration 780 : Cost Function : 0.4619998942666548
Iteration 790 : Cost Function : 0.46198752920352243
Iteration 800 : Cost Function : 0.46197592428325956
Iteration 810 : Cost Function : 0.4619650308227031
Iteration 820 : Cost Function : 0.46195480341475154
Iteration 830 : Cost Function : 0.46194519969443737
Iteration 840 : Cost Function : 0.46193618012291526
Iteration 850 : Cost Function : 0.4619277077878777
Iteration 860 : Cost Function : 0.4619197482190477
Iteration 870 : Cost Function : 0.46191226921751577
Iteration 880 : Cost Function : 0.4619052406978016
Iteration 890 : Cost Function : 0.46189863454161756
Iteration 900 : Cost Function : 0.46189242446240025
Iteration 910 : Cost Function : 0.46188658587976
Iteration 920 : Cost Function : 0.4618810958030651
Iteration 930 : Cost Function : 0.461875932723453
Iteration 940 : Cost Function : 0.461871076513612
Iteration 950 : Cost Function : 0.4618665083347371
Iteration 960 : Cost Function : 0.4618622105501109
Iteration 970 : Cost Function : 0.4618581666448061
Iteration 980 : Cost Function : 0.46185436115104944
Iteration 990 : Cost Function : 0.461850779578819
Iteration 1000 : Cost Function : 0.46184740835128774
Iteration 1010 : Cost Function : 0.4618442347447522
Iteration 1020 : Cost Function : 0.46184124683271577
Iteration 1030 : Cost Function : 0.4618384334338234
Iteration 1040 : Cost Function : 0.4618357840633649
Iteration 1050 : Cost Function : 0.46183328888808933
Iteration 1060 : Cost Function : 0.4618309386840918
Iteration 1070 : Cost Function : 0.46182872479755016
Iteration 1080 : Cost Function : 0.46182663910811106
Iteration 1090 : Cost Function : 0.46182467399473487
Iteration 1100 : Cost Function : 0.46182282230382543
Iteration 1110 : Cost Function : 0.4618210773194853
Iteration 1120 : Cost Function : 0.4618194327357457
Iteration 1130 : Cost Function : 0.4618178826306356
Iteration 1140 : Cost Function : 0.4618164214419591
Iteration 1150 : Cost Function : 0.46181504394466627
Iteration 1160 : Cost Function : 0.4618137452297047
Iteration 1170 : Cost Function : 0.46181252068425244
Iteration 1180 : Cost Function : 0.46181136597323635
Iteration 1190 : Cost Function : 0.46181027702204963
Iteration 1200 : Cost Function : 0.461809250000386
Iteration 1210 : Cost Function : 0.46180828130711615
Iteration 1220 : Cost Function : 0.46180736755613533
Iteration 1230 : Cost Function : 0.4618065055631184
Iteration 1240 : Cost Function : 0.46180569233311947
Iteration 1250 : Cost Function : 0.46180492504896287
Iteration 1260 : Cost Function : 0.46180420106037
Iteration 1270 : Cost Function : 0.46180351787377527
Iteration 1280 : Cost Function : 0.4618028731427852
Iteration 1290 : Cost Function : 0.461802264659238
Iteration 1300 : Cost Function : 0.4618016903448255
Iteration 1310 : Cost Function : 0.46180114824323937
Iteration 1320 : Cost Function : 0.4618006365128074
Iteration 1330 : Cost Function : 0.4618001534195912
Iteration 1340 : Cost Function : 0.4617996973309093
Iteration 1350 : Cost Function : 0.46179926670926574
Iteration 1360 : Cost Function : 0.4617988601066515
Iteration 1370 : Cost Function : 0.4617984761591992
Iteration 1380 : Cost Function : 0.4617981135821662
Iteration 1390 : Cost Function : 0.46179777116522586
Iteration 1400 : Cost Function : 0.46179744776804854
Iteration 1410 : Cost Function : 0.46179714231615093
Iteration 1420 : Cost Function : 0.4617968537970005
Iteration 1430 : Cost Function : 0.4617965812563554
Iteration 1440 : Cost Function : 0.4617963237948292
Iteration 1450 : Cost Function : 0.4617960805646605
Iteration 1460 : Cost Function : 0.461795850766681
Iteration 1470 : Cost Function : 0.461795633647465
Iteration 1480 : Cost Function : 0.4617954284966513
Iteration 1490 : Cost Function : 0.46179523464442557
Iteration 1500 : Cost Function : 0.46179505145915417
Iteration 1510 : Cost Function : 0.46179487834516
Iteration 1520 : Cost Function : 0.4617947147406304
Iteration 1530 : Cost Function : 0.4617945601156508
Iteration 1540 : Cost Function : 0.461794413970355
Iteration 1550 : Cost Function : 0.46179427583318505
Iteration 1560 : Cost Function : 0.4617941452592555
Iteration 1570 : Cost Function : 0.4617940218288132
Iteration 1580 : Cost Function : 0.46179390514578894
Iteration 1590 : Cost Function : 0.4617937948364344
Iteration 1600 : Cost Function : 0.46179369054803976
Iteration 1610 : Cost Function : 0.46179359194772557
Iteration 1620 : Cost Function : 0.4617934987213067
Iteration 1630 : Cost Function : 0.4617934105722231
Iteration 1640 : Cost Function : 0.4617933272205315
Iteration 1650 : Cost Function : 0.46179324840195757
Iteration 1660 : Cost Function : 0.46179317386700325
Iteration 1670 : Cost Function : 0.46179310338010465
Iteration 1680 : Cost Function : 0.46179303671884103
Iteration 1690 : Cost Function : 0.4617929736731875
Iteration 1700 : Cost Function : 0.4617929140448134
Iteration 1710 : Cost Function : 0.46179285764641875
Iteration 1720 : Cost Function : 0.461792804301111
Iteration 1730 : Cost Function : 0.4617927538418174
Iteration 1740 : Cost Function : 0.4617927061107298
Iteration 1750 : Cost Function : 0.4617926609587838
Iteration 1760 : Cost Function : 0.46179261824516515
Iteration 1770 : Cost Function : 0.4617925778368472
Iteration 1780 : Cost Function : 0.46179253960815253
Iteration 1790 : Cost Function : 0.461792503440341
Iteration 1800 : Cost Function : 0.4617924692212211
Iteration 1810 : Cost Function : 0.4617924368447829
Iteration 1820 : Cost Function : 0.4617924062108529
Iteration 1830 : Cost Function : 0.4617923772247676
Iteration 1840 : Cost Function : 0.4617923497970663
Iteration 1850 : Cost Function : 0.46179232384320085
Iteration 1860 : Cost Function : 0.4617922992832622
Iteration 1870 : Cost Function : 0.4617922760417223
Iteration 1880 : Cost Function : 0.46179225404719076
Iteration 1890 : Cost Function : 0.4617922332321847
Iteration 1900 : Cost Function : 0.46179221353291233
Iteration 1910 : Cost Function : 0.46179219488906853
Iteration 1920 : Cost Function : 0.46179217724364124
Iteration 1930 : Cost Function : 0.4617921605427301
Iteration 1940 : Cost Function : 0.4617921447353738
Iteration 1950 : Cost Function : 0.4617921297733881
Iteration 1960 : Cost Function : 0.46179211561121264
Iteration 1970 : Cost Function : 0.46179210220576633
Iteration 1980 : Cost Function : 0.4617920895163108
Iteration 1990 : Cost Function : 0.4617920775043214
Iteration 2000 : Cost Function : 0.46179206613336543
Iteration 2010 : Cost Function : 0.4617920553689878
Iteration 2020 : Cost Function : 0.4617920451786017
Iteration 2030 : Cost Function : 0.4617920355313865
Iteration 2040 : Cost Function : 0.46179202639819117
Iteration 2050 : Cost Function : 0.46179201775144263
Iteration 2060 : Cost Function : 0.46179200956505945
Iteration 2070 : Cost Function : 0.46179200181437013
Iteration 2080 : Cost Function : 0.4617919944760366
Iteration 2090 : Cost Function : 0.4617919875279805
Iteration 2100 : Cost Function : 0.4617919809493158
Iteration 2110 : Cost Function : 0.46179197472028255
Iteration 2120 : Cost Function : 0.46179196882218615
Iteration 2130 : Cost Function : 0.4617919632373392
Iteration 2140 : Cost Function : 0.46179195794900685
Iteration 2150 : Cost Function : 0.4617919529413551
Iteration 2160 : Cost Function : 0.4617919481994012
Iteration 2170 : Cost Function : 0.4617919437089685
Iteration 2180 : Cost Function : 0.4617919394566419
Iteration 2190 : Cost Function : 0.46179193542972674
Iteration 2200 : Cost Function : 0.4617919316162101
Iteration 2210 : Cost Function : 0.4617919280047232
Iteration 2220 : Cost Function : 0.4617919245845076
Iteration 2230 : Cost Function : 0.46179192134538105
Iteration 2240 : Cost Function : 0.4617919182777069
Iteration 2250 : Cost Function : 0.46179191537236497
Iteration 2260 : Cost Function : 0.461791912620723
Iteration 2270 : Cost Function : 0.46179191001461034
Iteration 2280 : Cost Function : 0.4617919075462941
Iteration 2290 : Cost Function : 0.46179190520845403
Iteration 2300 : Cost Function : 0.4617919029941615
Iteration 2310 : Cost Function : 0.46179190089685773
Iteration 2320 : Cost Function : 0.4617918989103343
Iteration 2330 : Cost Function : 0.4617918970287139
Iteration 2340 : Cost Function : 0.46179189524643316
Iteration 2350 : Cost Function : 0.4617918935582249
Iteration 2360 : Cost Function : 0.4617918919591031
Iteration 2370 : Cost Function : 0.46179189044434743
Iteration 2380 : Cost Function : 0.4617918890094884
Iteration 2390 : Cost Function : 0.46179188765029544
Iteration 2400 : Cost Function : 0.46179188636276236
Iteration 2410 : Cost Function : 0.46179188514309666
Iteration 2420 : Cost Function : 0.46179188398770715
Iteration 2430 : Cost Function : 0.46179188289319384
Iteration 2440 : Cost Function : 0.4617918818563374
Iteration 2450 : Cost Function : 0.4617918808740895
Iteration 2460 : Cost Function : 0.4617918799435638
Iteration 2470 : Cost Function : 0.46179187906202696
Iteration 2480 : Cost Function : 0.4617918782268912
Iteration 2490 : Cost Function : 0.4617918774357058
Iteration 2500 : Cost Function : 0.4617918766861498
Iteration 2510 : Cost Function : 0.4617918759760257
Iteration 2520 : Cost Function : 0.4617918753032523
Iteration 2530 : Cost Function : 0.4617918746658588
Iteration 2540 : Cost Function : 0.46179187406197875
Iteration 2550 : Cost Function : 0.46179187348984463
Iteration 2560 : Cost Function : 0.46179187294778234
Iteration 2570 : Cost Function : 0.4617918724342067
Iteration 2580 : Cost Function : 0.4617918719476161
Iteration 2590 : Cost Function : 0.4617918714865884
Iteration 2600 : Cost Function : 0.4617918710497772
Iteration 2610 : Cost Function : 0.4617918706359065
Iteration 2620 : Cost Function : 0.46179187024376833
Iteration 2630 : Cost Function : 0.4617918698722184
Iteration 2640 : Cost Function : 0.4617918695201729
Iteration 2650 : Cost Function : 0.4617918691866051
Iteration 2660 : Cost Function : 0.4617918688705428
Iteration 2670 : Cost Function : 0.46179186857106475
Iteration 2680 : Cost Function : 0.4617918682872988
Iteration 2690 : Cost Function : 0.4617918680184183
Iteration 2700 : Cost Function : 0.46179186776364073
Iteration 2710 : Cost Function : 0.4617918675222246
Iteration 2720 : Cost Function : 0.46179186729346744
Iteration 2730 : Cost Function : 0.4617918670767037
Iteration 2740 : Cost Function : 0.46179186687130364
Iteration 2750 : Cost Function : 0.4617918666766698
Iteration 2760 : Cost Function : 0.46179186649223675
Iteration 2770 : Cost Function : 0.4617918663174687
Iteration 2780 : Cost Function : 0.46179186615185797
Iteration 2790 : Cost Function : 0.46179186599492383
Iteration 2800 : Cost Function : 0.46179186584621074
Iteration 2810 : Cost Function : 0.4617918657052872
Iteration 2820 : Cost Function : 0.46179186557174423
Iteration 2830 : Cost Function : 0.4617918654451947
Iteration 2840 : Cost Function : 0.46179186532527144
Iteration 2850 : Cost Function : 0.4617918652116269
Iteration 2860 : Cost Function : 0.46179186510393205
Iteration 2870 : Cost Function : 0.46179186500187436
Iteration 2880 : Cost Function : 0.4617918649051585
Iteration 2890 : Cost Function : 0.46179186481350415
Iteration 2900 : Cost Function : 0.4617918647266462
Iteration 2910 : Cost Function : 0.461791864644333
Iteration 2920 : Cost Function : 0.46179186456632654
Iteration 2930 : Cost Function : 0.46179186449240095
Iteration 2940 : Cost Function : 0.4617918644223423
Iteration 2950 : Cost Function : 0.4617918643559483
Iteration 2960 : Cost Function : 0.4617918642930268
Iteration 2970 : Cost Function : 0.46179186423339574
Iteration 2980 : Cost Function : 0.461791864176883
Iteration 2990 : Cost Function : 0.461791864123325
Iteration 3000 : Cost Function : 0.4617918640725674
Iteration 3010 : Cost Function : 0.4617918640244633
Iteration 3020 : Cost Function : 0.4617918639788737
Iteration 3030 : Cost Function : 0.46179186393566724
Iteration 3040 : Cost Function : 0.46179186389471905
Iteration 3050 : Cost Function : 0.4617918638559108
Iteration 3060 : Cost Function : 0.46179186381913057
Iteration 3070 : Cost Function : 0.4617918637842724
Iteration 3080 : Cost Function : 0.4617918637512356
Iteration 3090 : Cost Function : 0.4617918637199247
Iteration 3100 : Cost Function : 0.46179186369024977
Iteration 3110 : Cost Function : 0.46179186366212494
Iteration 3120 : Cost Function : 0.46179186363546937
Iteration 3130 : Cost Function : 0.46179186361020597
Iteration 3140 : Cost Function : 0.4617918635862621
Iteration 3150 : Cost Function : 0.4617918635635687
Iteration 3160 : Cost Function : 0.46179186354206053
Iteration 3170 : Cost Function : 0.46179186352167534
Iteration 3180 : Cost Function : 0.46179186350235457
Iteration 3190 : Cost Function : 0.46179186348404266
Iteration 3200 : Cost Function : 0.4617918634666867
Iteration 3210 : Cost Function : 0.46179186345023693
Iteration 3220 : Cost Function : 0.4617918634346459
Iteration 3230 : Cost Function : 0.46179186341986883
Iteration 3240 : Cost Function : 0.46179186340586287
Iteration 3250 : Cost Function : 0.4617918633925881
Iteration 3260 : Cost Function : 0.46179186338000605
Iteration 3270 : Cost Function : 0.4617918633680808
Iteration 3280 : Cost Function : 0.46179186335677763
Iteration 3290 : Cost Function : 0.4617918633460646
Iteration 3300 : Cost Function : 0.4617918633359104
Iteration 3310 : Cost Function : 0.4617918633262861
Iteration 3320 : Cost Function : 0.4617918633171639
Iteration 3330 : Cost Function : 0.46179186330851757
Iteration 3340 : Cost Function : 0.4617918633003224
Iteration 3350 : Cost Function : 0.4617918632925548
Iteration 3360 : Cost Function : 0.46179186328519234
Iteration 3370 : Cost Function : 0.4617918632782139
Iteration 3380 : Cost Function : 0.46179186327159955
Iteration 3390 : Cost Function : 0.46179186326533017
Iteration 3400 : Cost Function : 0.46179186325938776
Iteration 3410 : Cost Function : 0.46179186325375526
Iteration 3420 : Cost Function : 0.4617918632484165
Iteration 3430 : Cost Function : 0.46179186324335625
Iteration 3440 : Cost Function : 0.46179186323855975
Iteration 3450 : Cost Function : 0.46179186323401344
Iteration 3460 : Cost Function : 0.4617918632297041
Iteration 3470 : Cost Function : 0.4617918632256196
Iteration 3480 : Cost Function : 0.46179186322174803
Iteration 3490 : Cost Function : 0.46179186321807825
Iteration 3500 : Cost Function : 0.46179186321459975
Iteration 3510 : Cost Function : 0.4617918632113027
Iteration 3520 : Cost Function : 0.4617918632081775
Iteration 3530 : Cost Function : 0.4617918632052152
Iteration 3540 : Cost Function : 0.4617918632024074
Iteration 3550 : Cost Function : 0.46179186319974586
Iteration 3560 : Cost Function : 0.461791863197223
Iteration 3570 : Cost Function : 0.4617918631948318
Iteration 3580 : Cost Function : 0.46179186319256516
Iteration 3590 : Cost Function : 0.4617918631904166
Iteration 3600 : Cost Function : 0.46179186318838006
Iteration 3610 : Cost Function : 0.46179186318644966
Iteration 3620 : Cost Function : 0.46179186318461996
Iteration 3630 : Cost Function : 0.4617918631828855
Iteration 3640 : Cost Function : 0.4617918631812415
Iteration 3650 : Cost Function : 0.461791863179683
Iteration 3660 : Cost Function : 0.4617918631782058
Iteration 3670 : Cost Function : 0.46179186317680565
Iteration 3680 : Cost Function : 0.46179186317547843
Iteration 3690 : Cost Function : 0.4617918631742203
Iteration 3700 : Cost Function : 0.4617918631730279
Iteration 3710 : Cost Function : 0.4617918631718974
Iteration 3720 : Cost Function : 0.4617918631708259
Iteration 3730 : Cost Function : 0.4617918631698102
Iteration 3740 : Cost Function : 0.46179186316884746
Iteration 3750 : Cost Function : 0.46179186316793475
Iteration 3760 : Cost Function : 0.46179186316706977
Iteration 3770 : Cost Function : 0.4617918631662497
Iteration 3780 : Cost Function : 0.46179186316547244
Iteration 3790 : Cost Function : 0.4617918631647357
Iteration 3800 : Cost Function : 0.46179186316403714
Iteration 3810 : Cost Function : 0.4617918631633752
Iteration 3820 : Cost Function : 0.46179186316274756

In [44]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
def metrics_row(name, y_true, y_pred):
    return {
        "Model": name,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred),
        "Recall": recall_score(y_true, y_pred),
        "F1": f1_score(y_true, y_pred),
    }
print(metrics_row("Logistic Regression (scratch)", y_test, y_pred))

{'Model': 'Logistic Regression (scratch)', 'Accuracy': 0.7532467532467533, 'Precision': 0.6666666666666666, 'Recall': 0.6181818181818182, 'F1': 0.6415094339622641}

MODEL 2: K-NN scratch

In [47]:
class KNearestNeighbours:
  def __init__(self,k=5):
    self.k = k
  def fit(self,X,y):
    self.X_train = X
    self.y_train = y.astype(int) # Convert y to integer type
    return self
  def predict(self,X):
    preds = np.empty(X.shape[0],dtype=int)
    for i,x in enumerate(X):
      dists = np.sqrt(np.sum((self.X_train-x)**2,axis=1))
      nearest_dists_index = np.argsort(dists)[:self.k]
      nearest_labels = self.y_train[nearest_dists_index]
      bruh = np.bincount(nearest_labels)
      preds[i] = np.argmax(bruh)
    return preds

In [52]:
y_pred = KNearestNeighbours(4).fit(X_train_std_knn.values, y_train.values).predict(X_test_std_knn.values)

In [53]:
print(metrics_row("KNN (scratch)" , y_test, y_pred))

{'Model': 'KNN (scratch)', 'Accuracy': 0.7272727272727273, 'Precision': 0.6511627906976745, 'Recall': 0.509090909090909, 'F1': 0.5714285714285714}