In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age','Outcome']
df = pd.read_csv(url, names=columns)
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [25]:
from sklearn.model_selection import train_test_split
X=df.drop('Outcome',axis=1)
y=df['Outcome']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train = X_train.copy()
X_test = X_test.copy()

This dataset is in need of some preprocessing.
Values that are 0 in columns other than Pregnancies and Outcome are actually NaN

In [26]:
nancols = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']
X_train[nancols] = X_train[nancols].replace(0,np.nan)
X_train.head()
X_test[nancols] = X_test[nancols].replace(0,np.nan)
X_test.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
668,6,98,58.0,33.0,190.0,34.0,0.430,43
324,2,112,75.0,32.0,NaN,35.7,0.148,21
624,2,108,64.0,NaN,NaN,30.8,0.158,21
690,8,107,80.0,NaN,NaN,24.6,0.856,34
473,7,136,90.0,NaN,NaN,29.9,0.210,50

In [27]:
#time to impute the NaNs with the median
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="median")
X_train_imp = imputer.fit_transform(X_train)
X_test_imp = imputer.transform(X_test)

In [28]:
#scaling values
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_std_lr = pd.DataFrame(scaler.fit_transform(X_train_imp), columns=X_train.columns, index=X_train.index)
X_test_std_lr = pd.DataFrame(scaler.transform(X_test_imp), columns=X_test.columns, index=X_test.index)
X_train_std_knn = X_train_std_lr.copy()
X_test_std_knn = X_test_std_lr.copy()

MODEL 1: LOGISTIC REGRESSION FROM SCRATCH

In [29]:
class LogisticRegression:
  def __init__(self, lr=0.01, iterations=5000, threshold=0.5):
    self.lr = lr
    self.iterations = iterations
    self.threshold = threshold

  @staticmethod
  def sigmoid(z):
    z = np.clip(z,-500,500)
    return (1.0/(1.0 + np.exp(-z)))

  def fit(self, X, y):
    self.w = np.zeros(X.shape[1])
    self.b=0
    for i in range(self.iterations):
      z = X@self.w + self.b
      p = self.sigmoid(z)
      error = p - y
      grad_w = (X.T@error)/X.shape[0]
      grad_b = error.mean()
      self.w = self.w - self.lr*grad_w
      self.b = self.b - self.lr*grad_b
      cost_function = -np.mean(y*np.log(p) + (1-y)*np.log(1-p))
      if(i%10==0):
        print(f"Iteration {i} : Cost Function : {cost_function}")
    return self
  def predict(self,X):
    return (self.sigmoid(X@self.w  +self.b) >= self.threshold).astype(int)

In [31]:
y_pred = LogisticRegression(0.05,10000).fit(X_train_std_lr,y_train).predict(X_test_std_lr)

Iteration 0 : Cost Function : 0.6931471805599453
Iteration 10 : Cost Function : 0.6300261566970795
Iteration 20 : Cost Function : 0.5900042004990463
Iteration 30 : Cost Function : 0.5632507343894727
Iteration 40 : Cost Function : 0.544426453049504
Iteration 50 : Cost Function : 0.5305897700804222
Iteration 60 : Cost Function : 0.520049527801397
Iteration 70 : Cost Function : 0.5117854503059018
Iteration 80 : Cost Function : 0.5051530662917356
Iteration 90 : Cost Function : 0.4997280855712699
Iteration 100 : Cost Function : 0.4952207979658583
Iteration 110 : Cost Function : 0.4914269800995418
Iteration 120 : Cost Function : 0.488198618127945
Iteration 130 : Cost Function : 0.4854258128423432
Iteration 140 : Cost Function : 0.48302522787388646
Iteration 150 : Cost Function : 0.4809324958552222
Iteration 160 : Cost Function : 0.47909709258043476
Iteration 170 : Cost Function : 0.4774787933256968
Iteration 180 : Cost Function : 0.47604516943222214
Iteration 190 : Cost Function : 0.4747697848572547
Iteration 200 : Cost Function : 0.4736308737894658
Iteration 210 : Cost Function : 0.4726103553518087
Iteration 220 : Cost Function : 0.4716930887345922
Iteration 230 : Cost Function : 0.47086630262796264
Iteration 240 : Cost Function : 0.4701191529085204
Iteration 250 : Cost Function : 0.46944237599566724
Iteration 260 : Cost Function : 0.4688280144703314
Iteration 270 : Cost Function : 0.468269197906043
Iteration 280 : Cost Function : 0.46775996633250055
Iteration 290 : Cost Function : 0.4672951269390228
Iteration 300 : Cost Function : 0.4668701369275182
Iteration 310 : Cost Function : 0.46648100710780227
Iteration 320 : Cost Function : 0.46612422207268983
Iteration 330 : Cost Function : 0.4657966737202749
Iteration 340 : Cost Function : 0.46549560559256586
Iteration 350 : Cost Function : 0.46521856603403333
Iteration 360 : Cost Function : 0.4649633685840398
Iteration 370 : Cost Function : 0.4647280583348342
Iteration 380 : Cost Function : 0.4645108832345888
Iteration 390 : Cost Function : 0.4643102695095462
Iteration 400 : Cost Function : 0.46412480053317745
Iteration 410 : Cost Function : 0.46395319859259004
Iteration 420 : Cost Function : 0.4637943091002914
Iteration 430 : Cost Function : 0.4636470868781278
Iteration 440 : Cost Function : 0.4635105842038563
Iteration 450 : Cost Function : 0.4633839403624997
Iteration 460 : Cost Function : 0.4632663724868384
Iteration 470 : Cost Function : 0.4631571675059802
Iteration 480 : Cost Function : 0.46305567504943085
Iteration 490 : Cost Function : 0.46296130117762946
Iteration 500 : Cost Function : 0.46287350282944806
Iteration 510 : Cost Function : 0.4627917828934276
Iteration 520 : Cost Function : 0.462715685823122
Iteration 530 : Cost Function : 0.46264479372833195
Iteration 540 : Cost Function : 0.4625787228836119
Iteration 550 : Cost Function : 0.4625171206035385
Iteration 560 : Cost Function : 0.4624596624410978
Iteration 570 : Cost Function : 0.4624060496713753
Iteration 580 : Cost Function : 0.46235600702770624
Iteration 590 : Cost Function : 0.4623092806616863
Iteration 600 : Cost Function : 0.46226563630207723
Iteration 610 : Cost Function : 0.46222485759077003
Iteration 620 : Cost Function : 0.4621867445766533
Iteration 630 : Cost Function : 0.4621511123505588
Iteration 640 : Cost Function : 0.46211778980646523
Iteration 650 : Cost Function : 0.462086618515884
Iteration 660 : Cost Function : 0.46205745170386553
Iteration 670 : Cost Function : 0.462030153316387
Iteration 680 : Cost Function : 0.46200459717003173
Iteration 690 : Cost Function : 0.4619806661758819
Iteration 700 : Cost Function : 0.46195825163043186
Iteration 710 : Cost Function : 0.46193725256710105
Iteration 720 : Cost Function : 0.4619175751626147
Iteration 730 : Cost Function : 0.4618991321931226
Iteration 740 : Cost Function : 0.4618818425354547
Iteration 750 : Cost Function : 0.4618656307093904
Iteration 760 : Cost Function : 0.4618504264572306
Iteration 770 : Cost Function : 0.4618361643573354
Iteration 780 : Cost Function : 0.46182278346862005
Iteration 790 : Cost Function : 0.46181022700329516
Iteration 800 : Cost Function : 0.4617984420253997
Iteration 810 : Cost Function : 0.46178737917290874
Iteration 820 : Cost Function : 0.461776992401409
Iteration 830 : Cost Function : 0.4617672387475216
Iteration 840 : Cost Function : 0.4617580781104205
Iteration 850 : Cost Function : 0.4617494730499455
Iteration 860 : Cost Function : 0.46174138859994607
Iteration 870 : Cost Function : 0.4617337920956138
Iteration 880 : Cost Function : 0.4617266530136723
Iteration 890 : Cost Function : 0.4617199428243908
Iteration 900 : Cost Function : 0.46171363485448325
Iteration 910 : Cost Function : 0.46170770416002826
Iteration 920 : Cost Function : 0.46170212740862693
Iteration 930 : Cost Function : 0.46169688277007653
Iteration 940 : Cost Function : 0.461691949814902
Iteration 950 : Cost Function : 0.4616873094201414
Iteration 960 : Cost Function : 0.4616829436818298
Iteration 970 : Cost Function : 0.4616788358336768
Iteration 980 : Cost Function : 0.4616749701714664
Iteration 990 : Cost Function : 0.4616713319827543
Iteration 1000 : Cost Function : 0.4616679074814649
Iteration 1010 : Cost Function : 0.46166468374702874
Iteration 1020 : Cost Function : 0.46166164866772164
Iteration 1030 : Cost Function : 0.4616587908879016
Iteration 1040 : Cost Function : 0.4616560997588587
Iteration 1050 : Cost Function : 0.46165356529301455
Iteration 1060 : Cost Function : 0.46165117812123224
Iteration 1070 : Cost Function : 0.4616489294530129
Iteration 1080 : Cost Function : 0.46164681103937183
Iteration 1090 : Cost Function : 0.46164481513820654
Iteration 1100 : Cost Function : 0.46164293448197813
Iteration 1110 : Cost Function : 0.4616411622475443
Iteration 1120 : Cost Function : 0.46163949202799376
Iteration 1130 : Cost Function : 0.46163791780634295
Iteration 1140 : Cost Function : 0.461636433930963
Iteration 1150 : Cost Function : 0.461635035092622
Iteration 1160 : Cost Function : 0.4616337163030273
Iteration 1170 : Cost Function : 0.4616324728747669
Iteration 1180 : Cost Function : 0.4616313004025553
Iteration 1190 : Cost Function : 0.4616301947456925
Iteration 1200 : Cost Function : 0.4616291520116571
Iteration 1210 : Cost Function : 0.461628168540755
Iteration 1220 : Cost Function : 0.46162724089175206
Iteration 1230 : Cost Function : 0.46162636582842853
Iteration 1240 : Cost Function : 0.4616255403069888
Iteration 1250 : Cost Function : 0.46162476146427334
Iteration 1260 : Cost Function : 0.46162402660671836
Iteration 1270 : Cost Function : 0.46162333320001353
Iteration 1280 : Cost Function : 0.46162267885941194
Iteration 1290 : Cost Function : 0.46162206134065065
Iteration 1300 : Cost Function : 0.46162147853143964
Iteration 1310 : Cost Function : 0.4616209284434842
Iteration 1320 : Cost Function : 0.46162040920500574
Iteration 1330 : Cost Function : 0.4616199190537277
Iteration 1340 : Cost Function : 0.46161945633029666
Iteration 1350 : Cost Function : 0.46161901947211204
Iteration 1360 : Cost Function : 0.46161860700753754
Iteration 1370 : Cost Function : 0.46161821755046767
Iteration 1380 : Cost Function : 0.4616178497952308
Iteration 1390 : Cost Function : 0.4616175025118039
Iteration 1400 : Cost Function : 0.46161717454131956
Iteration 1410 : Cost Function : 0.46161686479185027
Iteration 1420 : Cost Function : 0.46161657223444663
Iteration 1430 : Cost Function : 0.46161629589941855
Iteration 1440 : Cost Function : 0.46161603487284164
Iteration 1450 : Cost Function : 0.4616157882932756
Iteration 1460 : Cost Function : 0.46161555534868026
Iteration 1470 : Cost Function : 0.4616153352735185
Iteration 1480 : Cost Function : 0.4616151273460336
Iteration 1490 : Cost Function : 0.46161493088568933
Iteration 1500 : Cost Function : 0.4616147452507647
Iteration 1510 : Cost Function : 0.46161456983609184
Iteration 1520 : Cost Function : 0.46161440407092996
Iteration 1530 : Cost Function : 0.46161424741696516
Iteration 1540 : Cost Function : 0.4616140993664293
Iteration 1550 : Cost Function : 0.4616139594403321
Iteration 1560 : Cost Function : 0.46161382718679633
Iteration 1570 : Cost Function : 0.4616137021794927
Iteration 1580 : Cost Function : 0.46161358401616615
Iteration 1590 : Cost Function : 0.4616134723172508
Iteration 1600 : Cost Function : 0.4616133667245649
Iteration 1610 : Cost Function : 0.4616132669000832
Iteration 1620 : Cost Function : 0.46161317252478123
Iteration 1630 : Cost Function : 0.4616130832975479
Iteration 1640 : Cost Function : 0.4616129989341605
Iteration 1650 : Cost Function : 0.4616129191663208
Iteration 1660 : Cost Function : 0.4616128437407468
Iteration 1670 : Cost Function : 0.46161277241831744
Iteration 1680 : Cost Function : 0.4616127049732669
Iteration 1690 : Cost Function : 0.4616126411924259
Iteration 1700 : Cost Function : 0.4616125808745074
Iteration 1710 : Cost Function : 0.4616125238294326
Iteration 1720 : Cost Function : 0.46161246987769655
Iteration 1730 : Cost Function : 0.46161241884977094
Iteration 1740 : Cost Function : 0.4616123705855398
Iteration 1750 : Cost Function : 0.46161232493376914
Iteration 1760 : Cost Function : 0.4616122817516064
Iteration 1770 : Cost Function : 0.46161224090410874
Iteration 1780 : Cost Function : 0.46161220226379834
Iteration 1790 : Cost Function : 0.46161216571024316
Iteration 1800 : Cost Function : 0.4616121311296619
Iteration 1810 : Cost Function : 0.4616120984145508
Iteration 1820 : Cost Function : 0.461612067463333
Iteration 1830 : Cost Function : 0.46161203818002666
Iteration 1840 : Cost Function : 0.4616120104739324
Iteration 1850 : Cost Function : 0.4616119842593383
Iteration 1860 : Cost Function : 0.46161195945524275
Iteration 1870 : Cost Function : 0.4616119359850909
Iteration 1880 : Cost Function : 0.4616119137765281
Iteration 1890 : Cost Function : 0.46161189276116626
Iteration 1900 : Cost Function : 0.46161187287436317
Iteration 1910 : Cost Function : 0.4616118540550151
Iteration 1920 : Cost Function : 0.4616118362453603
Iteration 1930 : Cost Function : 0.4616118193907944
Iteration 1940 : Cost Function : 0.46161180343969505
Iteration 1950 : Cost Function : 0.4616117883432576
Iteration 1960 : Cost Function : 0.4616117740553394
Iteration 1970 : Cost Function : 0.46161176053231234
Iteration 1980 : Cost Function : 0.46161174773292496
Iteration 1990 : Cost Function : 0.4616117356181709
Iteration 2000 : Cost Function : 0.46161172415116586
Iteration 2010 : Cost Function : 0.46161171329703016
Iteration 2020 : Cost Function : 0.46161170302277893
Iteration 2030 : Cost Function : 0.4616116932972185
Iteration 2040 : Cost Function : 0.4616116840908475
Iteration 2050 : Cost Function : 0.46161167537576386
Iteration 2060 : Cost Function : 0.461611667125578
Iteration 2070 : Cost Function : 0.4616116593153294
Iteration 2080 : Cost Function : 0.4616116519214085
Iteration 2090 : Cost Function : 0.461611644921483
Iteration 2100 : Cost Function : 0.4616116382944281
Iteration 2110 : Cost Function : 0.4616116320202602
Iteration 2120 : Cost Function : 0.46161162608007517
Iteration 2130 : Cost Function : 0.461611620455989
Iteration 2140 : Cost Function : 0.46161161513108273
Iteration 2150 : Cost Function : 0.4616116100893496
Iteration 2160 : Cost Function : 0.461611605315645
Iteration 2170 : Cost Function : 0.4616116007956407
Iteration 2180 : Cost Function : 0.4616115965157793
Iteration 2190 : Cost Function : 0.46161159246323313
Iteration 2200 : Cost Function : 0.46161158862586443
Iteration 2210 : Cost Function : 0.46161158499218796
Iteration 2220 : Cost Function : 0.46161158155133536
Iteration 2230 : Cost Function : 0.4616115782930221
Iteration 2240 : Cost Function : 0.46161157520751567
Iteration 2250 : Cost Function : 0.4616115722856059
Iteration 2260 : Cost Function : 0.46161156951857624
Iteration 2270 : Cost Function : 0.46161156689817784
Iteration 2280 : Cost Function : 0.4616115644166034
Iteration 2290 : Cost Function : 0.46161156206646425
Iteration 2300 : Cost Function : 0.46161155984076707
Iteration 2310 : Cost Function : 0.46161155773289253
Iteration 2320 : Cost Function : 0.4616115557365759
Iteration 2330 : Cost Function : 0.4616115538458872
Iteration 2340 : Cost Function : 0.4616115520552132
Iteration 2350 : Cost Function : 0.4616115503592409
Iteration 2360 : Cost Function : 0.4616115487529411
Iteration 2370 : Cost Function : 0.4616115472315526
Iteration 2380 : Cost Function : 0.4616115457905689
Iteration 2390 : Cost Function : 0.46161154442572366
Iteration 2400 : Cost Function : 0.461611543132978
Iteration 2410 : Cost Function : 0.4616115419085085
Iteration 2420 : Cost Function : 0.4616115407486953
Iteration 2430 : Cost Function : 0.46161153965011154
Iteration 2440 : Cost Function : 0.4616115386095128
Iteration 2450 : Cost Function : 0.4616115376238275
Iteration 2460 : Cost Function : 0.4616115366901472
Iteration 2470 : Cost Function : 0.46161153580571873
Iteration 2480 : Cost Function : 0.46161153496793467
Iteration 2490 : Cost Function : 0.46161153417432665
Iteration 2500 : Cost Function : 0.46161153342255773
Iteration 2510 : Cost Function : 0.4616115327104145
Iteration 2520 : Cost Function : 0.4616115320358016
Iteration 2530 : Cost Function : 0.46161153139673483
Iteration 2540 : Cost Function : 0.4616115307913352
Iteration 2550 : Cost Function : 0.46161153021782364
Iteration 2560 : Cost Function : 0.46161152967451535
Iteration 2570 : Cost Function : 0.46161152915981474
Iteration 2580 : Cost Function : 0.4616115286722113
Iteration 2590 : Cost Function : 0.46161152821027385
Iteration 2600 : Cost Function : 0.46161152777264786
Iteration 2610 : Cost Function : 0.4616115273580502
Iteration 2620 : Cost Function : 0.4616115269652656
Iteration 2630 : Cost Function : 0.4616115265931432
Iteration 2640 : Cost Function : 0.4616115262405931
Iteration 2650 : Cost Function : 0.4616115259065834
Iteration 2660 : Cost Function : 0.4616115255901363
Iteration 2670 : Cost Function : 0.46161152529032595
Iteration 2680 : Cost Function : 0.4616115250062755
Iteration 2690 : Cost Function : 0.4616115247371545
Iteration 2700 : Cost Function : 0.4616115244821762
Iteration 2710 : Cost Function : 0.46161152424059554
Iteration 2720 : Cost Function : 0.46161152401170713
Iteration 2730 : Cost Function : 0.46161152379484244
Iteration 2740 : Cost Function : 0.4616115235893683
Iteration 2750 : Cost Function : 0.46161152339468514
Iteration 2760 : Cost Function : 0.4616115232102249
Iteration 2770 : Cost Function : 0.4616115230354497
Iteration 2780 : Cost Function : 0.4616115228698499
Iteration 2790 : Cost Function : 0.46161152271294276
Iteration 2800 : Cost Function : 0.461611522564271
Iteration 2810 : Cost Function : 0.4616115224234014
Iteration 2820 : Cost Function : 0.46161152228992386
Iteration 2830 : Cost Function : 0.46161152216344964
Iteration 2840 : Cost Function : 0.46161152204361044
Iteration 2850 : Cost Function : 0.4616115219300576
Iteration 2860 : Cost Function : 0.4616115218224608
Iteration 2870 : Cost Function : 0.46161152172050685
Iteration 2880 : Cost Function : 0.4616115216238995
Iteration 2890 : Cost Function : 0.4616115215323577
Iteration 2900 : Cost Function : 0.4616115214456154
Iteration 2910 : Cost Function : 0.4616115213634204
Iteration 2920 : Cost Function : 0.46161152128553407
Iteration 2930 : Cost Function : 0.4616115212117301
Iteration 2940 : Cost Function : 0.46161152114179416
Iteration 2950 : Cost Function : 0.4616115210755233
Iteration 2960 : Cost Function : 0.4616115210127248
Iteration 2970 : Cost Function : 0.4616115209532168
Iteration 2980 : Cost Function : 0.46161152089682644
Iteration 2990 : Cost Function : 0.4616115208433901
Iteration 3000 : Cost Function : 0.4616115207927528
Iteration 3010 : Cost Function : 0.4616115207447678
Iteration 3020 : Cost Function : 0.46161152069929595
Iteration 3030 : Cost Function : 0.46161152065620537
Iteration 3040 : Cost Function : 0.46161152061537114
Iteration 3050 : Cost Function : 0.46161152057667504
Iteration 3060 : Cost Function : 0.4616115205400049
Iteration 3070 : Cost Function : 0.4616115205052546
Iteration 3080 : Cost Function : 0.4616115204723235
Iteration 3090 : Cost Function : 0.461611520441116
Iteration 3100 : Cost Function : 0.46161152041154196
Iteration 3110 : Cost Function : 0.4616115203835157
Iteration 3120 : Cost Function : 0.46161152035695624
Iteration 3130 : Cost Function : 0.46161152033178654
Iteration 3140 : Cost Function : 0.461611520307934
Iteration 3150 : Cost Function : 0.46161152028532937
Iteration 3160 : Cost Function : 0.46161152026390745
Iteration 3170 : Cost Function : 0.4616115202436063
Iteration 3180 : Cost Function : 0.461611520224367
Iteration 3190 : Cost Function : 0.46161152020613416
Iteration 3200 : Cost Function : 0.4616115201888551
Iteration 3210 : Cost Function : 0.46161152017247964
Iteration 3220 : Cost Function : 0.46161152015696066
Iteration 3230 : Cost Function : 0.46161152014225326
Iteration 3240 : Cost Function : 0.46161152012831497
Iteration 3250 : Cost Function : 0.46161152011510553
Iteration 3260 : Cost Function : 0.46161152010258677
Iteration 3270 : Cost Function : 0.4616115200907225
Iteration 3280 : Cost Function : 0.46161152007947864
Iteration 3290 : Cost Function : 0.4616115200688225
Iteration 3300 : Cost Function : 0.4616115200587235
Iteration 3310 : Cost Function : 0.4616115200491524
Iteration 3320 : Cost Function : 0.4616115200400815
Iteration 3330 : Cost Function : 0.4616115200314848
Iteration 3340 : Cost Function : 0.46161152002333733
Iteration 3350 : Cost Function : 0.4616115200156157
Iteration 3360 : Cost Function : 0.4616115200082976
Iteration 3370 : Cost Function : 0.4616115200013621
Iteration 3380 : Cost Function : 0.4616115199947888
Iteration 3390 : Cost Function : 0.46161151998855915
Iteration 3400 : Cost Function : 0.46161151998265476
Iteration 3410 : Cost Function : 0.46161151997705907
Iteration 3420 : Cost Function : 0.4616115199717557
Iteration 3430 : Cost Function : 0.46161151996672933
Iteration 3440 : Cost Function : 0.4616115199619657
Iteration 3450 : Cost Function : 0.4616115199574508
Iteration 3460 : Cost Function : 0.4616115199531718
Iteration 3470 : Cost Function : 0.4616115199491162
Iteration 3480 : Cost Function : 0.4616115199452725
Iteration 3490 : Cost Function : 0.46161151994162963
Iteration 3500 : Cost Function : 0.461611519938177
Iteration 3510 : Cost Function : 0.4616115199349047
Iteration 3520 : Cost Function : 0.4616115199318032
Iteration 3530 : Cost Function : 0.46161151992886373
Iteration 3540 : Cost Function : 0.46161151992607774
Iteration 3550 : Cost Function : 0.46161151992343735
Iteration 3560 : Cost Function : 0.46161151992093463
Iteration 3570 : Cost Function : 0.4616115199185627
Iteration 3580 : Cost Function : 0.46161151991631466
Iteration 3590 : Cost Function : 0.461611519914184
Iteration 3600 : Cost Function : 0.46161151991216454
Iteration 3610 : Cost Function : 0.46161151991025057
Iteration 3620 : Cost Function : 0.4616115199084365
Iteration 3630 : Cost Function : 0.461611519906717
Iteration 3640 : Cost Function : 0.4616115199050875
Iteration 3650 : Cost Function : 0.4616115199035429
Iteration 3660 : Cost Function : 0.461611519902079
Iteration 3670 : Cost Function : 0.46161151990069144
Iteration 3680 : Cost Function : 0.4616115198993764
Iteration 3690 : Cost Function : 0.46161151989813
Iteration 3700 : Cost Function : 0.4616115198969486
Iteration 3710 : Cost Function : 0.4616115198958288
Iteration 3720 : Cost Function : 0.4616115198947675
Iteration 3730 : Cost Function : 0.46161151989376165
Iteration 3740 : Cost Function : 0.4616115198928082
Iteration 3750 : Cost Function : 0.4616115198919046
Iteration 3760 : Cost Function : 0.46161151989104826
Iteration 3770 : Cost Function : 0.4616115198902363
Iteration 3780 : Cost Function : 0.4616115198894669
Iteration 3790 : Cost Function : 0.46161151988873766
Iteration 3800 : Cost Function : 0.46161151988804644
Iteration 3810 : Cost Function : 0.46161151988739135
Iteration 3820 : Cost Function : 0.46161151988677035
Iteration 3830 : Cost Function : 0.4616115198861818

In [32]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
def metrics_row(name, y_true, y_pred):
    return {
        "Model": name,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred),
        "Recall": recall_score(y_true, y_pred),
        "F1": f1_score(y_true, y_pred),
    }
print(metrics_row("Logistic Regression (scratch)", y_test, y_pred))

{'Model': 'Logistic Regression (scratch)', 'Accuracy': 0.7532467532467533, 'Precision': 0.6666666666666666, 'Recall': 0.6181818181818182, 'F1': 0.6415094339622641}

MODEL 2: K-NN scratch

In [33]:
class KNearestNeighbours:
  def __init__(self,k=5):
    self.k = k
  def fit(self,X,y):
    self.X_train = X
    self.y_train = y.astype(int) # Convert y to integer type
    return self
  def predict(self,X):
    preds = np.empty(X.shape[0],dtype=int)
    for i,x in enumerate(X):
      dists = np.sqrt(np.sum((self.X_train-x)**2,axis=1))
      nearest_dists_index = np.argsort(dists)[:self.k]
      nearest_labels = self.y_train[nearest_dists_index]
      bruh = np.bincount(nearest_labels)
      preds[i] = np.argmax(bruh)
    return preds

In [34]:
y_pred = KNearestNeighbours(4).fit(X_train_std_knn.values, y_train.values).predict(X_test_std_knn.values)

In [35]:
print(metrics_row("KNN (scratch)" , y_test, y_pred))

{'Model': 'KNN (scratch)', 'Accuracy': 0.7337662337662337, 'Precision': 0.6521739130434783, 'Recall': 0.5454545454545454, 'F1': 0.594059405940594}

MODEL 3 : GAUSSIAN NAIVE BAYES FROM SCRATCH

In [36]:
class GaussianNB:
    def fit(self, X, y):
        self.classes = np.unique(y)
        n_features = X.shape[1]
        self.mean = {}
        self.var = {}
        self.priors = {}
        for c in self.classes:
            Xc = X[y == c]
            self.mean[c] = Xc.mean(axis=0)
            self.var[c] = Xc.var(axis=0) + 1e-9
            self.priors[c] = Xc.shape[0] / X.shape[0]
        return self

    def _log_gaussian(self, X, mean, var):
        return -0.5 * np.log(2 * np.pi * var) - ((X - mean) ** 2) / (2 * var)

    def predict_log_proba(self, X):
        log_probs = np.zeros((X.shape[0], len(self.classes)))
        for idx, c in enumerate(self.classes):
            log_likelihood = self._log_gaussian(X, self.mean[c], self.var[c]).sum(axis=1)
            log_probs[:, idx] = np.log(self.priors[c]) + log_likelihood
        return log_probs

    def predict(self, X):
        log_probs = self.predict_log_proba(X)
        return self.classes[np.argmax(log_probs, axis=1)]

In [37]:
y_pred = GaussianNB().fit(X_train.values, y_train.values).predict(X_test.values)

In [38]:
print(metrics_row("Naive Bayes (scratch)" , y_test, y_pred))

{'Model': 'Naive Bayes (scratch)', 'Accuracy': 0.6428571428571429, 'Precision': 0.0, 'Recall': 0.0, 'F1': 0.0}

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

We can see that the priors part is dominated by a particular class , hence the model always selects the dominating class